name: sanity-check

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: check
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.18

      - name: build
        run: pip install poetry; poetry install

      - name: pylint
        run: poetry run pylint src/

      - name: mypy
        run: poetry run mypy src/
